
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  DJANGO_SECRET: dGVzdDEyMzQ=
  OIDC_RP_CLIENT_ID: ZTJmMDZkMjMtNjE0NC00MjBmLTlmN2ItMzg0YzUzYmM5MjQ5
  OIDC_RP_CLIENT_SECRET: YmNiM2I1ZjYtNDg4My00M2Y5LWI5OTUtNGJiYmUyNDBiNGY1
